name: hjit
version: '0.1.0.0'
category: Compiler
author: Fabian Thorand
maintainer: f.thorand+haskell@gmail.com
copyright: 2017 Fabian Thorand
license: BSD3
github: fatho/hjit
extra-source-files:
- README.md

ghc-options:
  - "-Wall"

library:
  source-dirs: src
  exposed-modules:
  - Lib
  - HJit.CodeGen.AMD64
  - HJit.CodeGen.AMD64.ControlFlow
  - HJit.CodeGen.AMD64.Moves
  - HJit.CodeGen.AMD64.Prefixes
  - HJit.CodeGen.AMD64.Primitives
  - HJit.CodeGen.AMD64.Types
  - HJit.CodeGen.Assembler
  - HJit.CodeGen.Assembler.Internal
  - HJit.Memory
  - HJit.Memory.Types
  when:
  - condition: os(linux)
    cpp-options: -DOS_Linux
    other-modules: HJit.Memory.POSIX
  - condition: os(darwin)
    cpp-options: -DOS_Darwin
    other-modules: HJit.Memory.POSIX
  dependencies:
  - base >=4.7 && <5
  - bytestring
  - text
  - mtl
  - transformers
  - lens

executables:
  hjit-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hjit

tests:
  hjit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hjit

benchmarks:
  hjit-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hjit
    - criterion
